name: GuiLib
version: '${project.version}'
main: de.joshizockt.guilib.GuiLib
authors: [ JoshiZockt_ ]
description: Simple GUI Library for Minecraft Plugins
website: https://github.com/JoshiCodes/GuiLib
